name = "RepTracking"
uuid = "73804223-4a1d-48fa-9ea7-d91f84e5962d"
authors = ["Elysabeth <105363327+Lysmura@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
